"""add expires column

Revision ID: a2b6c4f6018a
Revises: 6404565c342e
Create Date: 2017-07-05 20:35:14.349564

"""
import time
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b6c4f6018a'
down_revision = '6404565c342e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docs', sa.Column('expires', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    op.execute("update docs set expires=%d" % int(time.time()))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('docs', 'expires')
    # ### end Alembic commands ###
